insert into nace_details(order_id,code,description,level,parent,reference_to_isic_rev4,ruling,this_item_also_includes,this_item_excludes,this_item_includes) 
values ('398481','A','AGRICULTURE,FORESTRY AND FISHING','1','','A','','','','This section includes the exploitation of vegetal and animal natural resources, comprising the activities of growing of crops,raising and breeding of animals,harvesting of timber and other plants,animals or animal products from a farm or their natural habitats');

insert into nace_details(order_id,code,description,level,parent,reference_to_isic_rev4,ruling,this_item_also_includes,this_item_excludes,this_item_includes) 
values ('398482','1','Corp and animal production,hunting and related service activities','2','A','1','','This division also includes service activities incidental to agriculture,as well as hunting,trapping and related activities.','Agriculture activities exclude any subsequent processing of the agriculture products (classified under divisions 10 and 11 (Manufacture of food products and beverages) and division 12 (Manufacturebof tobacco products)),beyond that needed to prepare them for the primary markets. The preparation of products for the primary market is included here. The division excludes field construction (e.g. agriculture land terracing,drainage,preparing rice paddies etc.) classified in section F (Construction) and buyers and cooperative associations engagged in the marketing of farm products classified in section G. Also excluded is the landscape care and maintenance','This division includes two basic activities,namely the production of corp products and production of animal products.coving also the form of arganic agriculture, the growing of genetically modified corps  and the raising of genetically modified animals. This division includes growing of corps in open fields as well in green housees. Grop 01.5(Mixed farming) breaks with the usual principles for identifying main activity. It accepts that many agriculture holding have reasonably balanced corp and animal production, and that it would be arbitrary to classify them in one category or the other.');

insert into nace_details(order_id,code,description,level,parent,reference_to_isic_rev4,ruling,this_item_also_includes,this_item_excludes,this_item_includes) 
values ('398483','1.1','Growing of non-perennial corps','3','1','11','','','','This group includes the growing of non-perennial corps,i.e. plants that do not last for more then two growing sessions.Included is the growing of these plants for the purpose of seed production.');

insert into nace_details(order_id,code,description,level,parent,reference_to_isic_rev4,ruling,this_item_also_includes,this_item_excludes,this_item_includes) 
values ('398484','1,11','Growing of cereals(expect rice), leguminous corps and oil seeds','4','1','111','','','This class excludes: - growing of rice, see 01.12 -growing of sweets corn,see 01.13 - growing of maize for fodder,see 01.19 - growing of oleaginous fruits,see 01.26','');

insert into nace_details(order_id,code,description,level,parent,reference_to_isic_rev4,ruling,this_item_also_includes,this_item_excludes,this_item_includes) 
values ('398485','1.12','Growing of rice','4','1.1','112','','','','This class includes: -growing of rice (including organic farming and the growing of genetically modified rice)');